export const lineChartCode = [
    '<template>',
    '  <v-card>',
    '    <v-card-title>Sales Trend</v-card-title>',
    '    <v-card-text>',
    '      <Line :data="chartData" :options="chartOptions" style="height: 400px;" />',
    '    </v-card-text>',
    '  </v-card>',
    '</template>',
    '',
    '<script setup lang="ts">',
    'import {',
    '  Chart as ChartJS,',
    '  CategoryScale,',
    '  LinearScale,',
    '  PointElement,',
    '  LineElement,',
    '  Title,',
    '  Tooltip,',
    '  Legend',
    '} from \'chart.js\'',
    'import { Line } from \'vue-chartjs\'',
    '',
    'ChartJS.register(',
    '  CategoryScale,',
    '  LinearScale,',
    '  PointElement,',
    '  LineElement,',
    '  Title,',
    '  Tooltip,',
    '  Legend',
    ')',
    '',
    'const chartData = {',
    '  labels: [\'Jan\', \'Feb\', \'Mar\', \'Apr\', \'May\', \'Jun\'],',
    '  datasets: [',
    '    {',
    '      label: \'Sales\',',
    '      backgroundColor: \'#1976d2\',',
    '      borderColor: \'#1976d2\',',
    '      data: [65, 59, 80, 81, 56, 95],',
    '      tension: 0.1',
    '    }',
    '  ]',
    '}',
    '',
    'const chartOptions = {',
    '  responsive: true,',
    '  maintainAspectRatio: false,',
    '  plugins: {',
    '    legend: {',
    '      position: \'top\' as const,',
    '    },',
    '    title: {',
    '      display: true,',
    '      text: \'Monthly Sales Data\'',
    '    }',
    '  }',
    '}',
    '</script>'
].join('\n')

export const barChartCode = [
    '<template>',
    '  <v-card>',
    '    <v-card-title>Product Sales</v-card-title>',
    '    <v-card-text>',
    '      <Bar :data="chartData" :options="chartOptions" style="height: 400px;" />',
    '    </v-card-text>',
    '  </v-card>',
    '</template>',
    '',
    '<script setup lang="ts">',
    'import {',
    '  Chart as ChartJS,',
    '  CategoryScale,',
    '  LinearScale,',
    '  BarElement,',
    '  Title,',
    '  Tooltip,',
    '  Legend',
    '} from \'chart.js\'',
    'import { Bar } from \'vue-chartjs\'',
    '',
    'ChartJS.register(',
    '  CategoryScale,',
    '  LinearScale,',
    '  BarElement,',
    '  Title,',
    '  Tooltip,',
    '  Legend',
    ')',
    '',
    'const chartData = {',
    '  labels: [\'Product A\', \'Product B\', \'Product C\', \'Product D\', \'Product E\'],',
    '  datasets: [',
    '    {',
    '      label: \'Sales\',',
    '      backgroundColor: [\'#ff5722\', \'#2196f3\', \'#4caf50\', \'#ff9800\', \'#9c27b0\'],',
    '      data: [12, 19, 3, 5, 2]',
    '    }',
    '  ]',
    '}',
    '',
    'const chartOptions = {',
    '  responsive: true,',
    '  maintainAspectRatio: false,',
    '  plugins: {',
    '    legend: {',
    '      position: \'top\' as const,',
    '    },',
    '    title: {',
    '      display: true,',
    '      text: \'Product Sales Comparison\'',
    '    }',
    '  }',
    '}',
    '</script>'
].join('\n')

export const pieChartCode = [
    '<template>',
    '  <v-card>',
    '    <v-card-title>Market Share</v-card-title>',
    '    <v-card-text>',
    '      <Pie :data="chartData" :options="chartOptions" style="height: 400px;" />',
    '    </v-card-text>',
    '  </v-card>',
    '</template>',
    '',
    '< script setup lang = "ts" > ',
    'import {',
    '  Chart as ChartJS,',
    '  ArcElement,',
    '  Tooltip,',
    '  Legend',
    '} from \'chart.js\'',
    'import { Pie } from \'vue-chartjs\'',
    '',
    'ChartJS.register(ArcElement, Tooltip, Legend)',
    '',
    'const chartData = {',
    '  labels: [\'Company A\', \'Company B\', \'Company C\', \'Others\'],',
    '  datasets: [',
    '    {',
    '      backgroundColor: [\'#ff6384\', \'#36a2eb\', \'#ffce56\', \'#4bc0c0\'],',
    '      data: [40, 25, 20, 15]',
    '    }',
    '  ]',
    '}',
    '',
    'const chartOptions = {',
    '  responsive: true,',
    '  maintainAspectRatio: false,',
    '  plugins: {',
    '    legend: {',
    '      position: \'right\' as const,',
    '    },',
    '    title: {',
    '      display: true,',
    '      text: \'Market Share Distribution\'',
    '    }',
    '  }',
    '}',
    '</script>'
].join('\n')

export const doughnutChartCode = [
    '<template>',
    '  <v-card>',
    '    <v-card-title>Revenue Breakdown</v-card-title>',
    '    <v-card-text>',
    '      <Doughnut :data="chartData" :options="chartOptions" style="height: 400px;" />',
    '    </v-card-text>',
    '  </v-card>',
    '</template>',
    '',
    '< script setup lang = "ts" > ',
    'import {',
    '  Chart as ChartJS,',
    '  ArcElement,',
    '  Tooltip,',
    '  Legend',
    '} from \'chart.js\'',
    'import { Doughnut } from \'vue-chartjs\'',
    '',
    'ChartJS.register(ArcElement, Tooltip, Legend)',
    '',
    'const chartData = {',
    '  labels: [\'Online Sales\', \'Retail Stores\', \'Wholesale\', \'Partnerships\'],',
    '  datasets: [',
    '    {',
    '      backgroundColor: [\'#ff9f40\', \'#ff6384\', \'#36a2eb\', \'#4bc0c0\'],',
    '      data: [45, 30, 15, 10],',
    '      borderWidth: 0',
    '    }',
    '  ]',
    '}',
    '',
    'const chartOptions = {',
    '  responsive: true,',
    '  maintainAspectRatio: false,',
    '  cutout: \'70%\',',
    '  plugins: {',
    '    legend: {',
    '      position: \'bottom\' as const,',
    '    },',
    '    title: {',
    '      display: true,',
    '      text: \'Revenue Sources\'',
    '    }',
    '  }',
    '}',
    '</script>'
].join('\n')

export const areaChartCode = [
    '<template>',
    '  <v-card>',
    '    <v-card-title>Website Traffic</v-card-title>',
    '    <v-card-text>',
    '      <Line :data="chartData" :options="chartOptions" style="height: 400px;" />',
    '    </v-card-text>',
    '  </v-card>',
    '</template>',
    '',
    '< script setup lang = "ts" > ',
    'import {',
    '  Chart as ChartJS,',
    '  CategoryScale,',
    '  LinearScale,',
    '  PointElement,',
    '  LineElement,',
    '  Title,',
    '  Tooltip,',
    '  Legend,',
    '  Filler',
    '} from \'chart.js\'',
    'import { Line } from \'vue-chartjs\'',
    '',
    'ChartJS.register(',
    '  CategoryScale,',
    '  LinearScale,',
    '  PointElement,',
    '  LineElement,',
    '  Title,',
    '  Tooltip,',
    '  Legend,',
    '  Filler',
    ')',
    '',
    'const chartData = {',
    '  labels: [\'Mon\', \'Tue\', \'Wed\', \'Thu\', \'Fri\', \'Sat\', \'Sun\'],',
    '  datasets: [',
    '    {',
    '      label: \'Visitors\',',
    '      backgroundColor: \'rgba(54, 162, 235, 0.2)\',',
    '      borderColor: \'rgba(54, 162, 235, 1)\',',
    '      data: [1200, 1900, 3000, 5000, 2300, 3200, 2800],',
    '      fill: true,',
    '      tension: 0.4',
    '    }',
    '  ]',
    '}',
    '',
    'const chartOptions = {',
    '  responsive: true,',
    '  maintainAspectRatio: false,',
    '  plugins: {',
    '    legend: {',
    '      position: \'top\' as const,',
    '    },',
    '    title: {',
    '      display: true,',
    '      text: \'Weekly Website Traffic\'',
    '    }',
    '  },',
    '  scales: {',
    '    y: {',
    '      beginAtZero: true',
    '    }',
    '  }',
    '}',
    '</script>'
].join('\n')

export const radarChartCode = [
    '<template>',
    ' <v-card>',
    ' <v-card-title>Performance Metrics</v-card-title>',
    ' <v-card-text>',
    '< Radar : data = "chartData" : options = "chartOptions" style = "height: 400px;" /> ',
    '</v-card-text>',
    ' </v-card>',
    '</template>',
    '',
    '< script setup lang = "ts" > ',
    'import {',
    '  Chart as ChartJS,',
    '  RadialLinearScale,',
    '  PointElement,',
    '  LineElement,',
    '  Filler,',
    '  Tooltip,',
    '  Legend',
    '} from \'chart.js\'',
    'import { Radar } from \'vue-chartjs\'',
    '',
    'ChartJS.register(',
    '  RadialLinearScale,',
    '  PointElement,',
    '  LineElement,',
    '  Filler,',
    '  Tooltip,',
    '  Legend',
    ')',
    '',
    'const chartData = {',
    '  labels: [\'Speed\', \'Reliability\', \'Comfort\', \'Safety\', \'Efficiency\', \'Cost\'],',
    '  datasets: [',
    '    {',
    '      label: \'Product A\',',
    '      backgroundColor: \'rgba(255, 99, 132, 0.2)\',',
    '      borderColor: \'rgba(255, 99, 132, 1)\',',
    '      pointBackgroundColor: \'rgba(255, 99, 132, 1)\',',
    '      data: [80, 90, 70, 85, 60, 90]',
    '    },',
    '    {',
    '      label: \'Product B\',',
    '      backgroundColor: \'rgba(54, 162, 235, 0.2)\',',
    '      borderColor: \'rgba(54, 162, 235, 1)\',',
    '      pointBackgroundColor: \'rgba(54, 162, 235, 1)\',',
    '      data: [70, 80, 90, 75, 85, 70]',
    '    }',
    '  ]',
    '}',
    '',
    'const chartOptions = {',
    '  responsive: true,',
    '  maintainAspectRatio: false,',
    '  plugins: {',
    '    legend: {',
    '      position: \'top\' as const,',
    '    },',
    '    title: {',
    '      display: true,',
    '      text: \'Product Comparison\'',
    '    }',
    '  },',
    '  scales: {',
    '    r: {',
    '      beginAtZero: true,',
    '      max: 100',
    '    }',
    '  }',
    '}',
    '</script>'
].join('\n')
